<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>NetWatch-Lite</AssemblyName>
    <RootNamespace>NetWatch</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ApplicationIcon>Assets/netwatch-lite.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src/**" />
    <EmbeddedResource Remove="src/**" />
    <None Remove="src/**" />
    <Content Remove="src/**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Data/config.backup.json" />
    <Content Remove="Data/config.json" />
    <Content Remove="Data/regions.json" />
    <Content Remove="Data/regions/**" />
    <Content Remove="Data/themes.json" />
    <Content Remove="publish/**" />
    <None Remove="Data/config.backup.json" />
    <None Remove="Data/config.json" />
    <None Remove="Data/regions.json" />
    <None Remove="Data/regions/**" />
    <None Remove="Data/themes.json" />
    <None Remove="publish/**" />
    <Content Update="Data/config.sample.json" Link="config.sample.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
